name = "telegram-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespace для хранения вайтлиста
[[kv_namespaces]]
binding = "WHITELIST"
id = "a1c878a2b6804aa6bcefa03e061318f5"

# Переменные окружения (секреты)
[vars]
# BOT_TOKEN и ADMIN_IDS нужно установить через wrangler secret put

# Для продакшена раскомментируйте:
# [env.production]
# name = "telegram-bot-prod"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true




